### ISSUE TITLE
Can't create Report

### ISSUE THREAD

**Issue by farahmad** [jaymegordo/SMSEventLog#101]
- 

<details>
<summary>Traceback
</summary>
<p>

Paste error text here:
Traceback (most recent call last):
  File "smseventlog\gui\multithread.py", line 34, in run
  File "smseventlog\utils\word.py", line 418, in create_word
  File "smseventlog\utils\word.py", line 378, in create_word
  File "docx\document.py", line 135, in save
  File "docx\parts\document.py", line 111, in save
  File "docx\opc\package.py", line 172, in save
  File "docx\opc\pkgwriter.py", line 32, in write
  File "docx\opc\phys_pkg.py", line 141, in __init__
  File "zipfile.py", line 1239, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'P:\\Regional\\Fort McMurray\\BU-145-ShovelTechs\\Customer Equipment Files\\7152 - 12106\\Events\\2022\\7152 - 2022-03-22 - WO4563401 - LH Front Swing Failed\\7152 - 2022-03-22 - LH Front Swing Failed.docx' 
</p>
</details>

**Comment by farahmad** [comment]
Issue resolved. The path was not correct.
