### ISSUE TITLE
Email List not Refreshing - Giving Error.

### ISSUE THREAD

**Issue by farahmad** [jaymegordo/SMSEventLog#105]
When refreshing email list on v3.7.7

Traceback (most recent call last):
  File "smseventlog\gui\tables.py", line 1058, in show_refresh
  File "smseventlog\gui\refreshtables.py", line 551, in __init__
  File "smseventlog\gui\refreshtables.py", line 171, in add_features
  File "smseventlog\gui\refreshtables.py", line 196, in add_feature
KeyError: 'MineSite'

**Comment by jaymegordo** [comment]
@farahmad update to 3.7.9 this is fixed!

**Comment by farahmad** [comment]
@jaymegordo the last link in teams in for v3.7.7. Can you update the link in teams to download the v3.7.9
