### ISSUE TITLE
PLM report wont generate

### ISSUE THREAD

**Issue by tbeckiesms** [jaymegordo/SMSEventLog#113]
Trying to create a PLM report from the event log gives errors
- 

<details>
<summary>Traceback
</summary>
<p>

Paste error text here:

```pytb
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3621, in get_loc
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'f344'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "smseventlog\gui\multithread.py", line 34, in run
  File "smseventlog\data\internal\plm.py", line 120, in update_plm_single_unit
  File "smseventlog\data\internal\utils.py", line 370, in process_files
  File "smseventlog\eventfolders.py", line 37, in __init__
  File "pandas\core\indexing.py", line 967, in __getitem__
  File "pandas\core\indexing.py", line 1202, in _getitem_axis
  File "pandas\core\indexing.py", line 1153, in _get_label
  File "pandas\core\generic.py", line 3876, in xs
  File "pandas\core\indexes\base.py", line 3623, in get_loc
KeyError: 'f344'
```
</p>
</details>

**Comment by jaymegordo** [comment]
Think I fixed this, feel free to re open if issue still happens in `3.7.12`
