### ISSUE TITLE
Oil Samples Dont work in 3.7.7

### ISSUE THREAD

**Issue by tbeckiesms** [jaymegordo/SMSEventLog#94]
Cant refresh in the 'oil samples' tab or create a report and include the oil samples. Get error both times
- 
<details>
<summary>Traceback
</summary>
<p>

Paste error text here:
```pytb
Traceback (most recent call last):
  File "smseventlog\errors.py", line 112, in wrapper
  File "smseventlog\gui\tables.py", line 1123, in refresh
  File "smseventlog\gui\tables.py", line 200, in display_data
  File "smseventlog\gui\datamodel.py", line 114, in set_df
  File "smseventlog\gui\datamodel.py", line 238, in set_static_dfs
  File "smseventlog\gui\datamodel.py", line 251, in set_stylemap
  File "smseventlog\queries\__init__.py", line 497, in get_stylemap
  File "pandas\io\formats\style_render.py", line 200, in _compute
  File "pandas\io\formats\style.py", line 1424, in _apply
  File "smseventlog\styles.py", line 391, in highlight_flags
  File "smseventlog\styles.py", line 384, in highlight_multiple_vals
  File "pandas\core\frame.py", line 5276, in replace
  File "pandas\core\generic.py", line 6659, in replace
  File "pandas\core\frame.py", line 5276, in replace
  File "pandas\core\generic.py", line 6708, in replace
  File "pandas\core\internals\managers.py", line 458, in replace_list
  File "pandas\core\internals\managers.py", line 304, in apply
  File "pandas\core\internals\blocks.py", line 813, in replace_list
  File "pandas\core\internals\blocks.py", line 868, in _replace_coerce
  File "pandas\core\internals\blocks.py", line 691, in replace
  File "pandas\core\array_algos\putmask.py", line 57, in putmask_inplace
  File "pandas\core\arrays\masked.py", line 224, in __setitem__
  File "pandas\core\arrays\integer.py", line 336, in _coerce_to_array
  File "pandas\core\arrays\integer.py", line 228, in coerce_to_array
ValueError: invalid literal for int() with base 10: 'background-color: ;color: ;' 

```
</p>
</details>

**Comment by tbeckiesms** [comment]
Traceback (most recent call last):
  File "smseventlog\errors.py", line 112, in wrapper
  File "smseventlog\gui\tables.py", line 1123, in refresh
  File "smseventlog\gui\tables.py", line 200, in display_data
  File "smseventlog\gui\datamodel.py", line 114, in set_df
  File "smseventlog\gui\datamodel.py", line 238, in set_static_dfs
  File "smseventlog\gui\datamodel.py", line 251, in set_stylemap
  File "smseventlog\queries\__init__.py", line 497, in get_stylemap
  File "pandas\io\formats\style_render.py", line 200, in _compute
  File "pandas\io\formats\style.py", line 1424, in _apply
  File "smseventlog\styles.py", line 391, in highlight_flags
  File "smseventlog\styles.py", line 384, in highlight_multiple_vals
  File "pandas\core\frame.py", line 5276, in replace
  File "pandas\core\generic.py", line 6659, in replace
  File "pandas\core\frame.py", line 5276, in replace
  File "pandas\core\generic.py", line 6708, in replace
  File "pandas\core\internals\managers.py", line 458, in replace_list
  File "pandas\core\internals\managers.py", line 304, in apply
  File "pandas\core\internals\blocks.py", line 813, in replace_list
  File "pandas\core\internals\blocks.py", line 868, in _replace_coerce
  File "pandas\core\internals\blocks.py", line 691, in replace
  File "pandas\core\array_algos\putmask.py", line 57, in putmask_inplace
  File "pandas\core\arrays\masked.py", line 224, in __setitem__
  File "pandas\core\arrays\integer.py", line 336, in _coerce_to_array
  File "pandas\core\arrays\integer.py", line 228, in coerce_to_array
ValueError: invalid literal for int() with base 10: 'background-color: ;color: ;'
